// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Address defines model for Address.
type Address struct {
	City       string  `json:"city"`
	Country    string  `json:"country"`
	PostalCode string  `json:"postal_code"`
	State      string  `json:"state"`
	Street1    string  `json:"street_1"`
	Street2    *string `json:"street_2,omitempty"`
}

// VettingRequest defines model for VettingRequest.
type VettingRequest struct {
	BillingAddress *Address                `json:"billing_address,omitempty"`
	Email          openapi_types.Email     `json:"email"`
	IpAddress      string                  `json:"ip_address"`
	MailingAddress *Address                `json:"mailing_address,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Phone          *string                 `json:"phone,omitempty"`
	UserAgent      *string                 `json:"user_agent,omitempty"`
	WebhookUrl     *string                 `json:"webhook_url,omitempty"`
}

// VettingResponse defines model for VettingResponse.
type VettingResponse struct {
	CheckStatusUrl *string    `json:"check_status_url,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	JobId          *string    `json:"job_id,omitempty"`
	Status         *string    `json:"status,omitempty"`
}

// VettingResult defines model for VettingResult.
type VettingResult struct {
	Enrichment     *map[string]interface{} `json:"enrichment,omitempty"`
	JobId          *string                 `json:"job_id,omitempty"`
	Recommendation *string                 `json:"recommendation,omitempty"`
	RiskScore      *int                    `json:"risk_score,omitempty"`
	Status         *string                 `json:"status,omitempty"`
}

// SubmitBatchVettingJobsJSONBody defines parameters for SubmitBatchVettingJobs.
type SubmitBatchVettingJobsJSONBody = []VettingRequest

// SubmitVettingJobJSONRequestBody defines body for SubmitVettingJob for application/json ContentType.
type SubmitVettingJobJSONRequestBody = VettingRequest

// SubmitBatchVettingJobsJSONRequestBody defines body for SubmitBatchVettingJobs for application/json ContentType.
type SubmitBatchVettingJobsJSONRequestBody = SubmitBatchVettingJobsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a vetting job
	// (POST /v1/vetting)
	SubmitVettingJob(ctx echo.Context) error
	// Submit a batch of vetting jobs
	// (POST /v1/vetting/batch)
	SubmitBatchVettingJobs(ctx echo.Context) error
	// Check the status and results of a vetting job
	// (GET /v1/vetting/{job_id})
	GetVettingJob(ctx echo.Context, jobId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubmitVettingJob converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitVettingJob(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitVettingJob(ctx)
	return err
}

// SubmitBatchVettingJobs converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitBatchVettingJobs(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitBatchVettingJobs(ctx)
	return err
}

// GetVettingJob converts echo context to params.
func (w *ServerInterfaceWrapper) GetVettingJob(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "job_id" -------------
	var jobId string

	err = runtime.BindStyledParameterWithOptions("simple", "job_id", ctx.Param("job_id"), &jobId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter job_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVettingJob(ctx, jobId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/v1/vetting", wrapper.SubmitVettingJob, options.OperationMiddlewares["SubmitVettingJob"]...)
	router.POST(options.BaseURL+"/v1/vetting/batch", wrapper.SubmitBatchVettingJobs, options.OperationMiddlewares["SubmitBatchVettingJobs"]...)
	router.GET(options.BaseURL+"/v1/vetting/:job_id", wrapper.GetVettingJob, options.OperationMiddlewares["GetVettingJob"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFbfb9s2EP5XBK57ivwjXvcwPTXdgCFBgRXbsAFLPeEkni06Eo8hj24zw//7QEr+IVtx0a15isLj8T5+",
	"331Hb0RJjSGNmp3INsKVFTYQP2+ktOjip7Fk0LLC+F+p+Cn85SeDIhOOrdJLsU1FSV6zHY4Zcgx1XpLE",
	"wbhj4OciFpHz60vB2UBwmwqLj15ZlCK7PxyTthfYlexDO1xinu4OpGKFJYdqfyCz0stf8dGj43NmClXX",
	"Si9zOFD3yuJCZOKbyYHnSUfyZMfwNhXYgKrDfvwEjalD2RVVWhK+6VbGJTUiFQuyDbDIuoxUGGBGq0Um",
	"/r6H0T83o7+mox/G+bdXo/nVm6OV0fzqw4dxtzDfzNLtK5GeE6rMMfqzcCj6327YIIMEhpACUipWpKF+",
	"f8QfW48DpJuK9HBneIc2hyVqHgx/xKIiesi9jczumfNWnd/8pFt27B7RcbEhnCHtcMArFZYPeeg073ZA",
	"zn1jERhlDtzDKYFxxKrBIZ1WVORKPmsl74YdceEGvh7oaNRWlVXTUXxJt33jboSSqLkbEoacU0WNuYYm",
	"VL6jSic/EYbaGvkj2YeY4vK10SJbQO1wEOiFC1ssqWlQSwjg+i66effulz+HCLTKPeSuJIu9hOvZfq/S",
	"jEu0fUoPJ4d2r5FRDjbTCf6wpPSCIn7F8YCO+uTm/a1IxRqti+jF9Xg6noaqZFCDUSIT38WlaPYqwpis",
	"ryfrNr9jOQoURIkk3EqRid980SjuytxRIdoeR8dvSUZ1StK809aYWpUxebJyLY2tjT9n8pOpuO17KXRH",
	"XGgtEtHPprOvX72zYCwv0ZVWmbYdxB0VCZQlGkaZgJbJo0ePMlD8ejoNBfr7b/UaaiWTjqzEwFNNIKOu",
	"zjcNhDeuYzeBpNMhWVERtxxpMymAy+pzCr0Nmw4yuf+hk2Js3JcKFsb6p9s28/vpdN+8YC08vYSeX4Zy",
	"J+wQrr5wkciXlDrKmdDiWHN3JvqmnVXbUG6JA7L/jH1XGrDQIKN1Irs/hfh7hYnX6tFj0g7WhUIbMHCF",
	"sefCZBFZnA0iFd2c7cblqXLpkQqnQ2t+pur0BVwanplnPNpO2Shb++6gTPY/G6KCr88VDImaOFmQ16e6",
	"/Rhe38jT0dE2YnCBwVPvbrf/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
