// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Address defines model for Address.
type Address struct {
	City       string  `json:"city"`
	Country    string  `json:"country"`
	PostalCode string  `json:"postal_code"`
	State      string  `json:"state"`
	Street1    string  `json:"street_1"`
	Street2    *string `json:"street_2,omitempty"`
}

// VettingRequest defines model for VettingRequest.
type VettingRequest struct {
	BillingAddress *Address                `json:"billing_address,omitempty"`
	Email          openapi_types.Email     `json:"email"`
	IpAddress      string                  `json:"ip_address"`
	MailingAddress *Address                `json:"mailing_address,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	Phone          *string                 `json:"phone,omitempty"`
	UserAgent      *string                 `json:"user_agent,omitempty"`
	WebhookUrl     *string                 `json:"webhook_url,omitempty"`
}

// VettingResponse defines model for VettingResponse.
type VettingResponse struct {
	CheckStatusUrl *string    `json:"check_status_url,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	JobId          *string    `json:"job_id,omitempty"`
	Status         *string    `json:"status,omitempty"`
}

// SubmitVettingJobJSONRequestBody defines body for SubmitVettingJob for application/json ContentType.
type SubmitVettingJobJSONRequestBody = VettingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a vetting job
	// (POST /v1/vetting)
	SubmitVettingJob(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubmitVettingJob converts echo context to params.
func (w *ServerInterfaceWrapper) SubmitVettingJob(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SubmitVettingJob(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/v1/vetting", wrapper.SubmitVettingJob, options.OperationMiddlewares["SubmitVettingJob"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"rFQ9b9swEP0rwrWjGjlpJ23p5kxBC3QpCuFEnm06Eo8mjy6MwP+9ICXBX0oKFJ0s85F89z6kV1DcO7Zk",
	"JUD9CkFtqMf8+Ki1p5AfnWdHXgzlf8rIIf3KwRHUEMQbu4ZjCYqjFT+POQ6CXaNY0yweBOUtxBNJc/8e",
	"+DADHkvwtIvGk4b65+machAwUV6OdhLxq5wu5HZLShLbDxIxdv2NdpGC3DrTmq4zdt3gybqPnlZQw4fq",
	"5HM1mlxNDh9LoB5Nl/av2PcoUI8r5a1k487vv4HTsX+boSdBjYLpCGptxLDF7vlMofhIM7a4Ddv57GIg",
	"3+CarMzCv6ndML800V9qj97cKr/Kc/LnzI53IwuObaCZNm9IvTSpCzFMg9w22xMK6QblYk6NQp/E9DSX",
	"05bbxug3yx7DfGevFKQlY1ecNxvpEjZqKh6fl1DCnnwwbKGG+7vF3SLdz44sOgM1fM5LJTiUTSas9vfV",
	"fjifveChx8kRTIEvNdTwPba9kZHmiVsYrKcgX1nn91uxlTFVdK4zKh+utiENMn1G/ta9q9fpeBlxKlte",
	"GJLL0z8sHv4/+9iMTK8pKG+cDIY+cVugUuSEdIFWF7tIkXSy+MtikQgu9y/tHjuji9GswuGhY9Q51xD7",
	"HtPHcXS3wGLModhym9iPfwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
